CREATE TABLE Season(
    Id INT UNIQUE NOT NULL IDENTITY(1,1),
    Year INT UNIQUE NOT NULL,
    PRIMARY KEY(Id)
)

CREATE TABLE GrandPrix(
    Id INT UNIQUE NOT NULL IDENTITY(1,1),
    Name VARCHAR(255) NOT NULL,
	SeasonId INT NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY(SeasonId) REFERENCES Season(Id)
);

CREATE TABLE Track(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Continent VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	IsStreet BIT NOT NULL,
	GrandPrixId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(GrandPrixId) REFERENCES GrandPrix(Id)
);

CREATE TABLE Session(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Name VARCHAR(255) NOT NULL,
	GrandPrixId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(GrandPrixId) REFERENCES GrandPrix(Id)
);

CREATE TABLE Stats(
	IsRainy BIT NOT NULL,
	IsFastestLapGuessed BIT NOT NULL,
	IsWinnerGuessed BIT NOT NULL,
	SessionId INT NOT NULL,
	FOREIGN KEY(SessionId) REFERENCES Session(Id)
);

CREATE TABLE Email(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Email VARCHAR(320) NOT NULL
	PRIMARY KEY(Id)
);

CREATE TABLE ParticipantLoginData(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Username VARCHAR(32) NOT NULL UNIQUE,
	Password VARCHAR(60) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE Participant(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Name VARCHAR(255) NOT NULL,
	Surname VARCHAR(255) NOT NULL,
	Description VARCHAR(255),
	ProfilePicture NVARCHAR(MAX),
	UserId INT NOT NULL,
	EmailId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(UserId) REFERENCES ParticipantLoginData(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);

CREATE TABLE Points(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Number DECIMAL(6,2) NOT NULL,
	ParticipantId INT NOT NULL,
	SessionId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(SessionId) REFERENCES Session(Id),
	FOREIGN KEY(ParticipantId) REFERENCES Participant(Id)
);

CREATE TABLE Predictions(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	Driver1 VARCHAR(255),
	Driver2 VARCHAR(255),
	Driver3 VARCHAR(255),
	Driver4 VARCHAR(255),
	Driver5 VARCHAR(255),
	Driver6 VARCHAR(255),
	Driver7 VARCHAR(255),
	Driver8 VARCHAR(255),
	Driver9 VARCHAR(255),
	Driver10 VARCHAR(255),
	Driver11 VARCHAR(255),
	Driver12 VARCHAR(255),
	Driver13 VARCHAR(255),
	Driver14 VARCHAR(255),
	Driver15 VARCHAR(255),
	Driver16 VARCHAR(255),
	Driver17 VARCHAR(255),
	Driver18 VARCHAR(255),
	Driver19 VARCHAR(255),
	Driver20 VARCHAR(255),
	FastestLap VARCHAR(255),
	ParticipantId INT NOT NULL,
	SessionId INT NOT NULL,
	GrandPrixId INT NOT NULL,
	PointsId INT,
	PRIMARY KEY(Id),
	FOREIGN KEY(ParticipantId) REFERENCES Participant(Id),
	FOREIGN KEY(SessionId) REFERENCES Session(Id),
	FOREIGN KEY(GrandPrixId) REFERENCES GrandPrix(Id),
	FOREIGN KEY(PointsId) REFERENCES Points(Id)
);

CREATE TABLE Joker(
	Id INT UNIQUE NOT NULL IDENTITY(1,1),
	ParticipantId INT NOT NULL,
	GrandPrixId INT NOT NULL,
	FOREIGN KEY(ParticipantId) REFERENCES Participant(Id),
	FOREIGN KEY(GrandPrixId) REFERENCES GrandPrix(Id)
);
